sudo: required
dist: xenial
os: linux
language: cpp
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "A8eKoO929vALzUzirYk7VP1znIKyGHiM53sD5863AqZy7Ww6TGY1VYpZCf+ai+5JbQPt/QENJ03qYuCpIuPlsoEqHmsy5V7kgPpHQ1/5nWI9dWlyZlkMLBV+D2dFIELoa0gTeXpPf/j8nHSnSvWTStaGFKIKskMPgBdWDO21cOhldW9pO6bDBnxnfS4UwL+p35UgaxX7ANQd/yiitJqJ2Zk+NwabAb3wU5OYb8iN47W9H28OkLOb4jz/GChRpCfFSUKKmZtxUopdmuDT7HyjrRe65NZPo/9BghG1xrLMUur4Sa/YfNtRWW4v+l88CyYoHZbPMg+z8TCq+C8F5tUmaAMMDU0Mih/WAYT3Ank04IzA3bMCz7e+ZhIT9+h7ahwmg9LykJTTuSJPPXJJxvQgABrvIsn/b0EoQIB+jk+faChZuq4zt/2tFLmTF4DMzXPGPKBBv9CHkPtD+0myBu9kjUKddnYgFzqMPH+a8mxRzoFycZrUxV6QWqj3DdKVe4WBGP9xJr18uMJsRFeDf4MV6jNlKGygfxXHB5FSLzBkOzeW4QVFPpbXKmxdQe6kjpYe5z2ee55zApHx3KVRxDDDxWMj0NMQHN9wJ17FTrbXNXAtItEv1Ja37xgwpAWQVNnGmdwVTseCoa+Xyz+e+Ia9TJ2tcJZZs7KhResefMMowkg="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get -qq update
  - sudo apt-get install -y sed python python3 python-autopep8 python3-pep8 tar wget cmake autoconf automake libtool curl make g++ unzip zlib1g-dev libpng12-dev vim-common qtbase5-dev
install:
  - wget https://github.com/google/protobuf/archive/v3.1.0.tar.gz
  - tar -xzvf v3.1.0.tar.gz
  - cd protobuf-3.1.0
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - wget https://vulkan.lunarg.com/sdk/download/1.0.30.0/linux/vulkansdk-linux-x86_64-1.0.30.0.run
  - chmod a+x vulkansdk-linux-x86_64-1.0.30.0.run
  - sudo ./vulkansdk-linux-x86_64-1.0.30.0.run
  - echo "VULKAN_SDK=$PWD/VulkanSDK/1.0.30.0/x86_64" >> ~/.bashrc
  - echo "export VULKAN_SDK" >> ~/.bashrc
  - echo "export PATH=$PWD/VulkanSDK/1.0.30.0/bin:$PATH" >> ~/.bashrc   
  - echo "export LD_LIBRARY_PATH=$PWD/VulkanSDK/1.0.30.0/lib:$LD_LIBRARY_PATH" >> ~/.bashrc
  - echo "export VK_LAYER_PATH=$PWD/VulkanSDK/1.0.30.0/etc/explicit_layer.d" >> ~/.bashrc
  - source ~/.bashrc
  - sudo ldconfig
before_script:
  - cmake -G "Unix Makefiles" .
script: make -j4 VERBOSE=1
notifications:
  email: false
addons:
  coverity_scan:
    project:
      name: "AeonGames/AeonEngine"
      description: "Aeon Games Game Engine"
    notification_email: kwizatz@aeongames.com
    build_command_prepend: "cmake -G "Unix Makefiles" .; make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan