version: 'aeonengine-{branch}-build-{build}'
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: x64
before_build:
- cmd: >-
    rem powershell -Command new-itemproperty -path "HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord"

    rem powershell -Command new-itemproperty -path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord"

    set VCPKG_DEFAULT_TRIPLET=x64-windows

    git clone https://github.com/Kwizatz/vcpkg.git
    
    cd vcpkg
    
    git checkout protobuf-c++17-iterator-fix-patch
    
    rem powershell -Command "(Get-Content ports\libpng\portfile.cmake) | ForEach-Object { $_ -replace \"libpng16/\", \"libpng16/older-releases/\" } | Set-Content ports\libpng\portfile.cmake"
    
    .\bootstrap-vcpkg.bat
    
    .\vcpkg integrate install
    
    .\vcpkg install protobuf zlib libpng glslang spirv-tools portaudio libogg libvorbis
    
    cd ..

    curl -LfsS -o VulkanSDK-1.0.54.0-Installer.exe https://vulkan.lunarg.com/sdk/download/1.0.54.0/windows/VulkanSDK-1.0.54.0-Installer.exe
    
    start "" /WAIT VulkanSDK-1.0.54.0-Installer.exe /S
    
    set VULKAN_SDK=C:\VulkanSDK\1.0.54.0
    
    mkdir build

    cd build

    cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE:filepath=C:/projects/aeonengine/vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR:path=C:/Qt/5.9.1/msvc2017_64/lib/cmake/Qt5 ..
build:
  project: build/AeonEngine.sln
  verbosity: minimal
