# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AeonEngine Development Blog
email: kwizatz@aeongames.com
description: > # this means to ignore newlines until "baseurl:"
  A page to gather thoughs regarding game engine development.
author: Rodrigo Hernandez
companyname: Aeon Games
about: AeonEngine Development Blog
logo: /AeonEngine/static/img/avatar.png
baseurl: "/AeonEngine"
url: "http://www.aeongames.com"
twitter_username: AeonKwizatz
github_username:  kwizatz
github: https://github.com/AeonGames/AeonEngine

markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
  shortname: aeonengine
    
allowsearch: true

# google_analytics: UA-72862926-1

share:
  twitter_username: AeonKwizatz
#  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
