name: 🚧🪟 Build on Windows (MSYS2)

on: [push, pull_request]

jobs:

  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64, runs-on: 'windows-latest' }
          - { icon: '🟨', sys: ucrt64, runs-on: 'windows-latest' }
          - { icon: '🟧', sys: clang64, runs-on: 'windows-latest' }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          make:p
          tools-git:p
          vulkan:p
          vulkan-devel:p
          qt6:p
          protobuf:p
          zlib:p
          libpng:p
          glslang:p
          portaudio:p
          libogg:p
          libvorbis:p
          cairo:p
          gtest:p

    - name: '🚧 Build'
      run: |
        cmake -G "MSYS Makefiles" -B build -DCMAKE_BUILD_TYPE=Release -DUSE_AEONGUI=ON
        cmake --build build --parallel "$(nproc)"

    - name: '🧪 Run TESTS'
      run: |
        cd build
        ctest --output-on-failure